-- PostgreSQL. Cədvəllər asılılıq ardıcıllığı ilə yaradılır.
-- Boş verilənlər bazasında bir dəfə icra edin.
BEGIN;

-- Şəhər adları ayrıca saxlanılır.
CREATE TABLE seherler (
    seher_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ad VARCHAR(100) NOT NULL,
    CONSTRAINT pk_seherler PRIMARY KEY (seher_id),
    CONSTRAINT uq_seher_ad UNIQUE (ad)
);

-- Telefon məcburi deyil; email və telefon təkrarlanmamalıdır.
CREATE TABLE musteriler (
    musteri_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ad VARCHAR(80) NOT NULL,
    soyad VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    telefon VARCHAR(30),
    seher_id INTEGER NOT NULL,
    CONSTRAINT pk_musteriler PRIMARY KEY (musteri_id),
    CONSTRAINT uq_musteri_email UNIQUE (email),
    CONSTRAINT uq_musteri_telefon UNIQUE (telefon),
    CONSTRAINT chk_musteri_email CHECK (POSITION('@' IN email) > 1),
    CONSTRAINT fk_musteri_seher FOREIGN KEY (seher_id)
        REFERENCES seherler (seher_id) ON DELETE RESTRICT
);

-- Məhsul kateqoriyaları.
CREATE TABLE kateqoriyalar (
    kateqoriya_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ad VARCHAR(100) NOT NULL,
    CONSTRAINT pk_kateqoriyalar PRIMARY KEY (kateqoriya_id),
    CONSTRAINT uq_kateqoriya_ad UNIQUE (ad)
);

-- Buradakı qiymət məhsulun cari qiymətidir.
CREATE TABLE mehsullar (
    mehsul_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ad VARCHAR(120) NOT NULL,
    kateqoriya_id INTEGER NOT NULL,
    qiymet NUMERIC(12, 2) NOT NULL,
    CONSTRAINT pk_mehsullar PRIMARY KEY (mehsul_id),
    CONSTRAINT uq_mehsul_ad UNIQUE (ad),
    CONSTRAINT chk_mehsul_qiymet CHECK (qiymet > 0),
    CONSTRAINT fk_mehsul_kateqoriya FOREIGN KEY (kateqoriya_id)
        REFERENCES kateqoriyalar (kateqoriya_id) ON DELETE RESTRICT
);

-- Kuryer məlumatları sifarişdən ayrılır.
CREATE TABLE kuryerler (
    kuryer_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ad VARCHAR(80) NOT NULL,
    soyad VARCHAR(100) NOT NULL,
    CONSTRAINT pk_kuryerler PRIMARY KEY (kuryer_id)
);

-- Müştəri silinərkən onun sifarişləri qorunur.
CREATE TABLE sifarisler (
    sifaris_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    musteri_id INTEGER NOT NULL,
    kuryer_id INTEGER NOT NULL,
    tarix DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Gözləmədə',
    CONSTRAINT pk_sifarisler PRIMARY KEY (sifaris_id),
    CONSTRAINT fk_sifaris_musteri FOREIGN KEY (musteri_id)
        REFERENCES musteriler (musteri_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sifaris_kuryer FOREIGN KEY (kuryer_id)
        REFERENCES kuryerler (kuryer_id) ON DELETE RESTRICT,
    CONSTRAINT chk_sifaris_status CHECK (
        status IN ('Gözləmədə', 'Göndərildi', 'Çatdırıldı', 'Ləğv edildi')
    )
);

-- N:M əlaqəsi; qiymət sifariş anına aiddir, cari qiymətdən asılı deyil.
CREATE TABLE sifaris_detallari (
    sifaris_id INTEGER NOT NULL,
    mehsul_id INTEGER NOT NULL,
    qiymet NUMERIC(12, 2) NOT NULL,
    miqdar INTEGER NOT NULL,
    CONSTRAINT pk_sifaris_detallari PRIMARY KEY (sifaris_id, mehsul_id),
    CONSTRAINT fk_detal_sifaris FOREIGN KEY (sifaris_id)
        REFERENCES sifarisler (sifaris_id) ON DELETE CASCADE,
    CONSTRAINT fk_detal_mehsul FOREIGN KEY (mehsul_id)
        REFERENCES mehsullar (mehsul_id) ON DELETE RESTRICT,
    CONSTRAINT chk_detal_qiymet CHECK (qiymet > 0),
    CONSTRAINT chk_detal_miqdar CHECK (miqdar >= 1)
);
COMMIT;
